CREATE TABLE [dbo].[Universities]
(
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(64) NOT NULL,
	[Address1] NVARCHAR(128) NOT NULL,
	[Address2] NVARCHAR(128),
	[City] NVARCHAR(32) NOT NULL,
	[State] NVARCHAR(16) NOT NULL,
	[Zip] NVARCHAR(16) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[NumberOfStudents] INT NOT NULL
)
